### ISSUE TITLE
Write readme

### ISSUE THREAD

**Issue by binaryplease** [binaryplease/base16-universal-manager#11]

**Comment by lhanson** [comment]
Looks like this could be closed since there's quite a bit of content in the Readme?

**Comment by binaryplease** [comment]
@lhanson true. Have not given much time to this project lately since no one seemed to be interested. I'll try to give it some work. Any PRs and further input like issues etc. are welcome too!

**Comment by lhanson** [comment]
I'm kind of surprised nobody else has been interested because it seems to me like exactly what I've been looking for! I'm excited to hopefully start putting it to use, so I'll probably be submitting some more PRs as I go. Thanks!

**Comment by binaryplease** [comment]
@lhanson  I'll gladly review and merge any PRs! Nice to see some interest.
