### ISSUE TITLE
Add flag to print configuration

### ISSUE THREAD

**Issue by lhanson** [binaryplease/base16-universal-manager#26]
It would be useful to be able to print current configuration without uncommenting and recompiling the application [here](https://github.com/binaryplease/base16-universal-manager/blob/04a605d230ac825c29af415954801419b23f4500/main.go#L34) . Perhaps there could be a `--print-config` option that does this on demand.

**Comment by binaryplease** [comment]
Should be easy to add, will try to do it tomorrow.
